#You are given two strings s and t.
#String t is generated by random shuffling string s and then add one more letter at a random position.
#Return the letter that was added to t.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for i in t:
            if s.count(i) != t.count(i):
                return i
'''
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        ans = 0
        for c in t:
            ans = ans + ord(c)
        for c in s:
            ans = ans - ord(c)
        return chr(ans)

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        return [i for i in t if s.count(i) != t.count(i)][0]

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for item in t:
            if item not in s:
                return item
'''